### ISSUE TITLE
Browser Module

### ISSUE THREAD

**Issue by spaquis** [misha130/ionic2-numericpicker#2]
Hi,
When i try to use this module on ionic 3.
I have this error : 
`core.es5.js:1084 ERROR Error: Uncaught (in promise): Error: BrowserModule has already been loaded`

When i remove BrowserModule from module.js it's work. 
Can you push a version without the import of BrowserModule ? 
Thanks in advance

**Comment by spaquis** [comment]
I succeed by creating my own module which import your component.
Thanks.

**Comment by misha130** [comment]
Done in 1.3.0
Thanks.
